services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: false  # Security best practice
    user: "${UID:-1000}:${GID:-1000}"  # Match host user permissions    
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
    restart: unless-stopped